### ISSUE TITLE
If app is backgrounded for some time, it does not come back to life

### ISSUE THREAD

**Issue by willcrick** [Esri/ecological-marine-unit-android#17]
I am assuming this happens when the app gets closed by the OS. So if you background the app, then use a memory hungry app, or just some other apps for a while, then click on the EMU app from the list of backgrounded apps (square button) i always get:

![screenshot_20170131-131451](https://cloud.githubusercontent.com/assets/2145578/22484720/901fca30-e7b7-11e6-9a71-95387156ca68.png)

I assume some state is not being saved to allow it to come back.

**Comment by doneill** [comment]
Closing, @willcrick you can re-open if you still see issues on certain devices.
